apiVersion: v1
kind: Service
metadata:
  name: kvstore-service
spec:
  type: NodePort
  selector:
    app: kvstore
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30000